## function to check pixels from a .csv with Easting and Northing columns from the UTM reference used in the associated raster files
## x needs to be a TimeStack i.e. one generated by bFastSpatial's processLandsatBatch.

cfd_checkPixel <- function(poi, file = villages_csv, strt = 2016, end = 2017){
 poi_test <- bfmPixel(x, cell = c(file$Easting[poi], file$Northing[poi]), start= 2016, monend=2017)
 plot(poi_test$bfm)
}
